### PR TITLE
Show course name on queue page

### LINKED ISSUE #31: show queue and course name on queue page
may be important to give some indication of which queue and course the user is on, esp now that it could be a bit easier to accidentally join the wrong queue from the homepage

### PR DESCRIPTION
**Pull request by nwalters512**
Like #232, but without modifying the existing API. We just load the course and display the name as soon as we can.

Closes #232, Closes #138, Closes #31

### CODE REVIEW

File: src/pages/queue.js [hunk 1]
```diff
@@ -38,22 +39,29 @@ class Queue extends React.Component {
...
   static pageTransitionDelayEnter = true
 
   componentDidMount() {
-    this.props.fetchQueue(this.props.queueId).then(() => {
+    this.props.fetchQueue(this.props.queueId).then(action => {
       if (this.props.pageTransitionReadyToEnter) {
         this.props.pageTransitionReadyToEnter()
       }
+      // We won't block the page from showing while we load the course - we'll
+      // simply slow the course name as soon as it's available
```
Comment (james9909) [inline src/pages/queue.js]: Slow -> show?
