### PR TITLE
Add support for fixed-location queues

### LINKED ISSUE #51: Allow a queue to be created with a fixed location
When creating a queue, the queue should be able to have either a "fixed location" or a "student-supplied" location.

If a queue has a "fixed location", students are unable to enter a custom location. 

If a queue has a "student supplied" location, students are able to enter a custom location.

### PR DESCRIPTION
**Pull request by nwalters512**
Fixes #51

### CODE REVIEW

File: api/queues.js [hunk 1]
```diff
@@ -40,6 +49,7 @@ router.post(
     const queue = Queue.build({
       name: data.name,
       location: data.location,
+      fixedLocation: data.fixedLocation === true,
```
Comment (genevievehelsel) [inline api/queues.js]: remove ' === true'

Comment (genevievehelsel) [reply api/queues.js]: .
